import type { MarketCsvRow } from './market-csv';
import { nextEventWindow } from './market-schedule';

function sqlEscape(value: string): string {
  return value.replace(/'/g, "''");
}

function sqlString(value: string | null | undefined): string {
  if (!value || !value.trim()) return 'null';
  return `'${sqlEscape(value.trim())}'`;
}

function rowValues(row: MarketCsvRow): string {
  const { start, end } = nextEventWindow(row.day_of_week, row.start_hour, row.end_hour, row.state);
  const description =
    row.description ||
    `Farmers market in ${row.city}, ${row.state}. Hours and vendors may vary — confirm with the organizer.`;

  return `(
    ${sqlString(row.name)},
    ${sqlString(description)},
    ${sqlString(row.organizer_name || `${row.city} Market`)},
    ${sqlString(row.address || null)},
    ${sqlString(row.city)},
    ${sqlString(row.state)},
    ${row.latitude},
    ${row.longitude},
    ${sqlString(start)},
    ${sqlString(end)},
    'upcoming',
    'public',
    ${sqlString(row.parking_info || 'Check with the market for parking details.')},
    ${sqlString(row.admission_info)}
  )`;
}

export function marketsToSql(rows: MarketCsvRow[], sourceLabel: string): string {
  const header = `-- Generated by Rooted market import pipeline
-- Source: ${sourceLabel}
-- Generated at: ${new Date().toISOString()}
-- Markets: ${rows.length}
--
-- Run in Supabase SQL Editor after phase4_events.sql (and phase12_admin.sql if using admin tools).
-- Safe to re-run: inserts are skipped when name + city + state already exist.

`;

  if (rows.length === 0) {
    return `${header}-- No rows to import.\n`;
  }

  const chunks: string[] = [header];
  const batchSize = 100;

  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const values = batch.map(rowValues).join(',\n    ');

    chunks.push(`insert into public.events
  (name, description, organizer_name, address, city, state, latitude, longitude,
   start_datetime, end_datetime, event_status, visibility_status, parking_info, admission_info)
select
  v.name,
  v.description,
  v.organizer_name,
  v.address,
  v.city,
  v.state,
  v.latitude,
  v.longitude,
  v.start_datetime::timestamptz,
  v.end_datetime::timestamptz,
  v.event_status,
  v.visibility_status,
  v.parking_info,
  v.admission_info
from (
  values
    ${values}
) as v(
  name, description, organizer_name, address, city, state, latitude, longitude,
  start_datetime, end_datetime, event_status, visibility_status, parking_info, admission_info
)
where not exists (
  select 1
  from public.events e
  where lower(e.name) = lower(v.name)
    and lower(coalesce(e.city, '')) = lower(v.city)
    and upper(coalesce(e.state, '')) = upper(v.state)
);

`);
  }

  return chunks.join('\n');
}

function usdaRowValues(row: MarketCsvRow): string {
  const { start, end, timezone } = nextEventWindow(
    row.day_of_week,
    row.start_hour,
    row.end_hour,
    row.state,
  );
  const website = row.website?.trim() ?? '';
  const hoursSummary = row.hours_summary?.trim() || `Typically ${row.day_of_week}s — confirm with organizer`;
  const syncMetadata = JSON.stringify({
    opening_hours: row.opening_hours ?? `Sa 08:00-13:00`,
    typical_day: row.day_of_week,
    runs_on_days: row.runs_on_days ?? [row.day_of_week],
    start_hour: row.start_hour,
    end_hour: row.end_hour,
    seasonal_schedule: row.seasonal_schedule ?? null,
    schedule_source: row.schedule_source ?? 'default',
    source: 'usda',
    zipcode: row.zipcode?.trim() || null,
    usda_directory: row.market_type ?? 'farmers_market',
    contact_name: row.contact_name ?? null,
    contact_phone: row.contact_phone ?? null,
    contact_email: row.contact_email ?? null,
    facebook_url: row.facebook_url ?? null,
    instagram_url: row.instagram_url ?? null,
    website: website || null,
  });

  return `(
    ${sqlString(row.external_id)},
    ${sqlString(row.name)},
    ${sqlString(row.description)},
    ${sqlString(row.organizer_name || `${row.city} Market`)},
    ${sqlString(row.address || null)},
    ${sqlString(row.city)},
    ${sqlString(row.state)},
    ${row.latitude},
    ${row.longitude},
    ${sqlString(start)},
    ${sqlString(end)},
    'upcoming',
    'public',
    ${sqlString(row.parking_info)},
    ${sqlString(row.admission_info)},
    ${sqlString(row.market_type ?? 'farmers_market')},
    ${sqlString(hoursSummary)},
    ${sqlString(website || null)},
    ${sqlString(row.extra_info ?? null)},
    'usda',
    ${sqlString(timezone)},
    ${sqlString(syncMetadata)}::jsonb
  )`;
}

/** SQL to switch the live catalog to USDA API markets (hides OSM/legacy public events). */
export const USDA_SWITCH_PREAMBLE = `-- Switch Rooted events catalog to USDA Local Food Directory API markets.
-- Hides existing public events that are not already tagged external_source = 'usda'.
update public.events
set visibility_status = 'draft',
    updated_at = now()
where visibility_status = 'public'
  and coalesce(external_source, '') <> 'usda';

`;

export function usdaMarketsToSql(
  rows: MarketCsvRow[],
  sourceLabel: string,
  options: { includeSwitch?: boolean } = {},
): string {
  const includeSwitch = options.includeSwitch ?? true;
  const switchSql = includeSwitch ? USDA_SWITCH_PREAMBLE : '';

  const header = `-- Generated by Rooted USDA market import
-- Source: ${sourceLabel}
-- Generated at: ${new Date().toISOString()}
-- Markets: ${rows.length}
--
-- Requires phase4_events.sql, phase13_market_agent.sql, phase14_market_details.sql.
-- Safe to re-run: upserts on (external_source, external_id); skips rows when the same market name + city + state is already public.

${switchSql}`;

  if (rows.length === 0) {
    return `${header}-- No rows to import.\n`;
  }

  const chunks: string[] = [header];
  const batchSize = 100;

  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const values = batch.map(usdaRowValues).join(',\n    ');

    chunks.push(`insert into public.events
  (external_id, name, description, organizer_name, address, city, state, latitude, longitude,
   start_datetime, end_datetime, event_status, visibility_status, parking_info, admission_info,
   market_type, hours_summary, website_url, extra_info, external_source, timezone, last_synced_at, sync_metadata)
select
  v.external_id,
  v.name,
  v.description,
  v.organizer_name,
  v.address,
  v.city,
  v.state,
  v.latitude,
  v.longitude,
  v.start_datetime::timestamptz,
  v.end_datetime::timestamptz,
  v.event_status,
  v.visibility_status,
  v.parking_info,
  v.admission_info,
  v.market_type,
  v.hours_summary,
  v.website_url,
  v.extra_info,
  v.external_source,
  v.timezone,
  now(),
  v.sync_metadata
from (
  values
    ${values}
) as v(
  external_id, name, description, organizer_name, address, city, state, latitude, longitude,
  start_datetime, end_datetime, event_status, visibility_status, parking_info, admission_info,
  market_type, hours_summary, website_url, extra_info, external_source, timezone, sync_metadata
)
where not exists (
  select 1
  from public.events e
  where e.visibility_status = 'public'
    and lower(regexp_replace(trim(e.name), '[^a-zA-Z0-9]', '', 'g'))
      = lower(regexp_replace(trim(v.name), '[^a-zA-Z0-9]', '', 'g'))
    and lower(trim(coalesce(e.city, ''))) = lower(trim(v.city))
    and upper(trim(coalesce(e.state, ''))) = upper(trim(v.state))
    and coalesce(e.external_id, '') <> v.external_id
)
on conflict (external_source, external_id)
where external_source is not null and external_id is not null
do update set
  name = excluded.name,
  description = excluded.description,
  organizer_name = excluded.organizer_name,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  start_datetime = excluded.start_datetime,
  end_datetime = excluded.end_datetime,
  event_status = excluded.event_status,
  visibility_status = excluded.visibility_status,
  parking_info = excluded.parking_info,
  admission_info = excluded.admission_info,
  market_type = excluded.market_type,
  hours_summary = excluded.hours_summary,
  website_url = excluded.website_url,
  extra_info = excluded.extra_info,
  timezone = excluded.timezone,
  last_synced_at = now(),
  sync_metadata = excluded.sync_metadata,
  updated_at = now();

`);
  }

  return chunks.join('\n');
}
