/** Major cities to query first per state (better Nominatim coverage than alphabetical CSV order). */
export const METRO_CITIES: Record<string, string[]> = {
  AL: ['Birmingham', 'Montgomery', 'Mobile', 'Huntsville', 'Tuscaloosa'],
  AK: ['Anchorage', 'Fairbanks', 'Juneau'],
  AZ: ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale', 'Tempe', 'Flagstaff'],
  AR: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Bentonville'],
  CA: ['Los Angeles', 'San Francisco', 'San Diego', 'Sacramento', 'San Jose', 'Oakland', 'Fresno'],
  CO: ['Denver', 'Colorado Springs', 'Boulder', 'Fort Collins', 'Aurora', 'Aspen', 'Littleton'],
  CT: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport'],
  DE: ['Wilmington', 'Dover', 'Newark'],
  DC: ['Washington'],
  FL: ['Miami', 'Orlando', 'Tampa', 'Jacksonville', 'Tallahassee', 'Fort Lauderdale'],
  GA: ['Atlanta', 'Savannah', 'Augusta', 'Athens', 'Macon'],
  HI: ['Honolulu', 'Hilo', 'Kailua'],
  ID: ['Boise', 'Idaho Falls', 'Coeur d\'Alene'],
  IL: ['Chicago', 'Springfield', 'Naperville', 'Peoria'],
  IN: ['Indianapolis', 'Fort Wayne', 'Bloomington', 'South Bend'],
  IA: ['Des Moines', 'Cedar Rapids', 'Iowa City', 'Davenport'],
  KS: ['Wichita', 'Kansas City', 'Topeka', 'Lawrence'],
  KY: ['Louisville', 'Lexington', 'Bowling Green'],
  LA: ['New Orleans', 'Baton Rouge', 'Lafayette', 'Shreveport'],
  ME: ['Portland', 'Bangor', 'Augusta'],
  MD: ['Baltimore', 'Annapolis', 'Frederick', 'Bethesda'],
  MA: ['Boston', 'Cambridge', 'Springfield', 'Worcester', 'Salem'],
  MI: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing', 'Traverse City'],
  MN: ['Minneapolis', 'Saint Paul', 'Duluth', 'Rochester'],
  MS: ['Jackson', 'Gulfport', 'Oxford', 'Hattiesburg'],
  MO: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia'],
  MT: ['Billings', 'Missoula', 'Bozeman', 'Helena'],
  NE: ['Omaha', 'Lincoln', 'Grand Island'],
  NV: ['Las Vegas', 'Reno', 'Carson City'],
  NH: ['Manchester', 'Portsmouth', 'Concord'],
  NJ: ['Newark', 'Jersey City', 'Trenton', 'Princeton', 'Atlantic City'],
  NM: ['Albuquerque', 'Santa Fe', 'Las Cruces', 'Taos'],
  NY: ['New York', 'Brooklyn', 'Buffalo', 'Rochester', 'Albany', 'Syracuse'],
  NC: ['Charlotte', 'Raleigh', 'Durham', 'Asheville', 'Wilmington'],
  ND: ['Fargo', 'Bismarck', 'Grand Forks'],
  OH: ['Columbus', 'Cleveland', 'Cincinnati', 'Dayton', 'Toledo'],
  OK: ['Oklahoma City', 'Tulsa', 'Norman', 'Stillwater'],
  OR: ['Portland', 'Eugene', 'Salem', 'Bend'],
  PA: ['Philadelphia', 'Pittsburgh', 'Harrisburg', 'Lancaster', 'Reading'],
  RI: ['Providence', 'Newport', 'Warwick'],
  SC: ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach'],
  SD: ['Sioux Falls', 'Rapid City', 'Pierre'],
  TN: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'],
  TX: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth', 'El Paso'],
  UT: ['Salt Lake City', 'Provo', 'Park City', 'St. George'],
  VT: ['Burlington', 'Montpelier', 'Brattleboro'],
  VA: ['Richmond', 'Virginia Beach', 'Norfolk', 'Charlottesville', 'Arlington'],
  WA: ['Seattle', 'Spokane', 'Tacoma', 'Bellingham', 'Olympia'],
  WV: ['Charleston', 'Morgantown', 'Huntington'],
  WI: ['Milwaukee', 'Madison', 'Green Bay', 'La Crosse'],
  WY: ['Cheyenne', 'Casper', 'Jackson', 'Laramie'],
};
