/**
 * exportBaselineMarketsCsv.ts
 *
 * Writes data/markets-baseline.csv — one well-known farmers market per US state
 * (+ DC), sourced from docs/supabase/phase5_seed_all_states_events.sql.
 * No API keys. Use as fallback when OSM fetch is unavailable.
 *
 *   npx tsx scripts/exportBaselineMarketsCsv.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { marketsToCsv, type MarketCsvRow } from './lib/market-csv';

const OUTPUT = resolve(process.cwd(), 'data/markets-baseline.csv');

const BASELINE: Omit<MarketCsvRow, 'external_id' | 'source' | 'day_of_week' | 'start_hour' | 'end_hour'>[] = [
  { name: 'Birmingham Farmers Market', description: 'Local farmers, makers, and food vendors gather weekly in Birmingham.', organizer_name: 'Birmingham Market Association', address: '1 Market Pl', city: 'Birmingham', state: 'AL', zipcode: '', latitude: 33.5186, longitude: -86.8104, parking_info: 'Public parking nearby.', admission_info: 'Free admission.' },
  { name: 'Anchorage Saturday Market', description: 'Alaskan growers and artisans with fresh produce and handmade goods.', organizer_name: 'Anchorage Market Association', address: '3rd Ave', city: 'Anchorage', state: 'AK', zipcode: '', latitude: 61.2181, longitude: -149.9003, parking_info: 'Street parking available.', admission_info: 'Free admission.' },
  { name: 'Phoenix Public Market', description: 'Desert-grown produce, local makers, and food trucks in downtown Phoenix.', organizer_name: 'Phoenix Market Association', address: '721 N Central Ave', city: 'Phoenix', state: 'AZ', zipcode: '', latitude: 33.4484, longitude: -112.074, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Little Rock Farmers Market', description: 'Arkansas farmers and crafters in the River Market district.', organizer_name: 'Little Rock Market Association', address: '400 President Clinton Ave', city: 'Little Rock', state: 'AR', zipcode: '', latitude: 34.7465, longitude: -92.2896, parking_info: 'Lot parking available.', admission_info: 'Free admission.' },
  { name: 'Los Angeles Farmers Market', description: 'A sprawling market with produce, makers, and street food in LA.', organizer_name: 'Los Angeles Market Association', address: '6333 W 3rd St', city: 'Los Angeles', state: 'CA', zipcode: '', latitude: 34.0522, longitude: -118.2437, parking_info: 'Paid lot parking.', admission_info: 'Free admission.' },
  { name: 'Cherry Creek Fresh Market', description: 'Colorado growers and artisans in the Cherry Creek neighborhood of Denver.', organizer_name: 'Denver Market Association', address: '3000 E 1st Ave', city: 'Denver', state: 'CO', zipcode: '', latitude: 39.7392, longitude: -104.9903, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Hartford Regional Market', description: 'New England farmers and food makers in Hartford.', organizer_name: 'Hartford Market Association', address: '101 Reserve Rd', city: 'Hartford', state: 'CT', zipcode: '', latitude: 41.7658, longitude: -72.6734, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Wilmington Farmers Market', description: 'Delaware growers and crafters along the Riverfront.', organizer_name: 'Wilmington Market Association', address: '815 Justison St', city: 'Wilmington', state: 'DE', zipcode: '', latitude: 39.7391, longitude: -75.5398, parking_info: 'Riverfront parking.', admission_info: 'Free admission.' },
  { name: 'Miami Community Market', description: 'Tropical produce, makers, and food vendors in Miami.', organizer_name: 'Miami Market Association', address: '301 SE 3rd Ave', city: 'Miami', state: 'FL', zipcode: '', latitude: 25.7617, longitude: -80.1918, parking_info: 'Paid garage parking.', admission_info: 'Free admission.' },
  { name: 'Atlanta Farmers Market', description: 'Georgia farmers and artisans in midtown Atlanta.', organizer_name: 'Atlanta Market Association', address: '999 Peachtree St NE', city: 'Atlanta', state: 'GA', zipcode: '', latitude: 33.749, longitude: -84.388, parking_info: 'Street and garage parking.', admission_info: 'Free admission.' },
  { name: 'Honolulu Farmers Market', description: 'Island-grown produce and local makers in Honolulu.', organizer_name: 'Honolulu Market Association', address: '777 Ward Ave', city: 'Honolulu', state: 'HI', zipcode: '', latitude: 21.3069, longitude: -157.8583, parking_info: 'Lot parking available.', admission_info: 'Free admission.' },
  { name: 'Boise Capital City Market', description: 'Idaho farmers and crafters in downtown Boise.', organizer_name: 'Boise Market Association', address: '8th St', city: 'Boise', state: 'ID', zipcode: '', latitude: 43.615, longitude: -116.2023, parking_info: 'Free street parking weekends.', admission_info: 'Free admission.' },
  { name: 'Chicago Green City Market', description: 'Midwest farmers and food makers near Lincoln Park.', organizer_name: 'Chicago Market Association', address: '1817 N Clark St', city: 'Chicago', state: 'IL', zipcode: '', latitude: 41.8781, longitude: -87.6298, parking_info: 'Paid garage parking.', admission_info: 'Free admission.' },
  { name: 'Indianapolis City Market', description: 'Indiana growers and artisans in downtown Indianapolis.', organizer_name: 'Indianapolis Market Association', address: '222 E Market St', city: 'Indianapolis', state: 'IN', zipcode: '', latitude: 39.7684, longitude: -86.1581, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Des Moines Farmers Market', description: 'Iowa farmers and makers in the Court Avenue district.', organizer_name: 'Des Moines Market Association', address: '300 Court Ave', city: 'Des Moines', state: 'IA', zipcode: '', latitude: 41.5868, longitude: -93.625, parking_info: 'Street and ramp parking.', admission_info: 'Free admission.' },
  { name: 'Wichita Old Town Market', description: 'Kansas growers and crafters in Old Town Wichita.', organizer_name: 'Wichita Market Association', address: '835 E 1st St N', city: 'Wichita', state: 'KS', zipcode: '', latitude: 37.6872, longitude: -97.3301, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Louisville Farmers Market', description: 'Kentucky farmers and food makers near NuLu.', organizer_name: 'Louisville Market Association', address: '700 E Market St', city: 'Louisville', state: 'KY', zipcode: '', latitude: 38.2527, longitude: -85.7585, parking_info: 'Street parking available.', admission_info: 'Free admission.' },
  { name: 'Crescent City Farmers Market', description: 'Louisiana growers and artisans in New Orleans.', organizer_name: 'New Orleans Market Association', address: '750 Carondelet St', city: 'New Orleans', state: 'LA', zipcode: '', latitude: 29.9511, longitude: -90.0715, parking_info: 'Paid lot parking.', admission_info: 'Free admission.' },
  { name: 'Portland Maine Farmers Market', description: 'New England farmers and makers in Deering Oaks Park.', organizer_name: 'Portland Market Association', address: '1 Deering Oaks', city: 'Portland', state: 'ME', zipcode: '', latitude: 43.6591, longitude: -70.2568, parking_info: 'Street parking nearby.', admission_info: 'Free admission.' },
  { name: 'Baltimore Farmers Market', description: 'Maryland farmers and crafters under the JFX.', organizer_name: 'Baltimore Market Association', address: '1100 Saratoga St', city: 'Baltimore', state: 'MD', zipcode: '', latitude: 39.2904, longitude: -76.6122, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Boston Public Market', description: 'New England growers and food makers in downtown Boston.', organizer_name: 'Boston Market Association', address: '100 Hanover St', city: 'Boston', state: 'MA', zipcode: '', latitude: 42.3601, longitude: -71.0589, parking_info: 'Paid garage parking; T accessible.', admission_info: 'Free admission.' },
  { name: 'Detroit Eastern Market', description: 'Michigan farmers and artisans in the historic Eastern Market.', organizer_name: 'Detroit Market Association', address: '2934 Russell St', city: 'Detroit', state: 'MI', zipcode: '', latitude: 42.3314, longitude: -83.0458, parking_info: 'Lot and street parking.', admission_info: 'Free admission.' },
  { name: 'Minneapolis Farmers Market', description: 'Minnesota farmers and makers near downtown Minneapolis.', organizer_name: 'Minneapolis Market Association', address: '312 E Lyndale Ave N', city: 'Minneapolis', state: 'MN', zipcode: '', latitude: 44.9778, longitude: -93.265, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Jackson Farmers Market', description: 'Mississippi growers and crafters in downtown Jackson.', organizer_name: 'Jackson Market Association', address: '929 High St', city: 'Jackson', state: 'MS', zipcode: '', latitude: 32.2988, longitude: -90.1848, parking_info: 'Free parking on-site.', admission_info: 'Free admission.' },
  { name: 'Kansas City River Market', description: 'Missouri farmers and food makers in the City Market.', organizer_name: 'Kansas City Market Association', address: '20 E 5th St', city: 'Kansas City', state: 'MO', zipcode: '', latitude: 39.0997, longitude: -94.5786, parking_info: 'Lot parking available.', admission_info: 'Free admission.' },
  { name: 'Billings Farmers Market', description: 'Montana growers and artisans in downtown Billings.', organizer_name: 'Billings Market Association', address: '2722 3rd Ave N', city: 'Billings', state: 'MT', zipcode: '', latitude: 45.7833, longitude: -108.5007, parking_info: 'Street parking available.', admission_info: 'Free admission.' },
  { name: 'Omaha Farmers Market', description: 'Nebraska farmers and makers in the Old Market.', organizer_name: 'Omaha Market Association', address: '511 S 11th St', city: 'Omaha', state: 'NE', zipcode: '', latitude: 41.2565, longitude: -95.9345, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Las Vegas Farmers Market', description: 'Nevada growers and food vendors in downtown Las Vegas.', organizer_name: 'Las Vegas Market Association', address: '525 E Fremont St', city: 'Las Vegas', state: 'NV', zipcode: '', latitude: 36.1699, longitude: -115.1398, parking_info: 'Paid garage parking.', admission_info: 'Free admission.' },
  { name: 'Manchester Farmers Market', description: 'New Hampshire farmers and crafters in downtown Manchester.', organizer_name: 'Manchester Market Association', address: '1 Elm St', city: 'Manchester', state: 'NH', zipcode: '', latitude: 42.9956, longitude: -71.4548, parking_info: 'Street parking available.', admission_info: 'Free admission.' },
  { name: 'Newark Farmers Market', description: 'New Jersey growers and makers in downtown Newark.', organizer_name: 'Newark Market Association', address: '1 Mulberry St', city: 'Newark', state: 'NJ', zipcode: '', latitude: 40.7357, longitude: -74.1724, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Albuquerque Growers Market', description: 'New Mexico farmers and artisans near Old Town.', organizer_name: 'Albuquerque Market Association', address: '2000 Mountain Rd NW', city: 'Albuquerque', state: 'NM', zipcode: '', latitude: 35.0844, longitude: -106.6504, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Union Square Greenmarket', description: 'New York growers and food makers in Union Square.', organizer_name: 'New York Market Association', address: 'E 17th St & Broadway', city: 'New York', state: 'NY', zipcode: '', latitude: 40.7128, longitude: -74.006, parking_info: 'Subway accessible; paid garages.', admission_info: 'Free admission.' },
  { name: 'Charlotte Regional Market', description: 'North Carolina farmers and crafters in Charlotte.', organizer_name: 'Charlotte Market Association', address: '1801 Yorkmont Rd', city: 'Charlotte', state: 'NC', zipcode: '', latitude: 35.2271, longitude: -80.8431, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Fargo Farmers Market', description: 'North Dakota growers and makers in downtown Fargo.', organizer_name: 'Fargo Market Association', address: '210 Broadway N', city: 'Fargo', state: 'ND', zipcode: '', latitude: 46.8772, longitude: -96.7898, parking_info: 'Street parking available.', admission_info: 'Free admission.' },
  { name: 'Columbus Farmers Market', description: 'Ohio farmers and food vendors in the Short North.', organizer_name: 'Columbus Market Association', address: '59 Spruce St', city: 'Columbus', state: 'OH', zipcode: '', latitude: 39.9612, longitude: -82.9988, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Oklahoma City Farmers Market', description: 'Oklahoma growers and crafters in OKC.', organizer_name: 'Oklahoma City Market Association', address: '311 S Klein Ave', city: 'Oklahoma City', state: 'OK', zipcode: '', latitude: 35.4676, longitude: -97.5164, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Portland Saturday Market', description: 'Oregon farmers and artisans along the waterfront.', organizer_name: 'Portland Market Association', address: '2 SW Naito Pkwy', city: 'Portland', state: 'OR', zipcode: '', latitude: 45.5152, longitude: -122.6784, parking_info: 'MAX accessible; paid parking.', admission_info: 'Free admission.' },
  { name: 'Reading Terminal Market', description: 'Pennsylvania growers and food makers in Philadelphia.', organizer_name: 'Philadelphia Market Association', address: '1136 Arch St', city: 'Philadelphia', state: 'PA', zipcode: '', latitude: 39.9526, longitude: -75.1652, parking_info: 'Paid garage parking.', admission_info: 'Free admission.' },
  { name: 'Providence Farmers Market', description: 'Rhode Island farmers and crafters in downtown Providence.', organizer_name: 'Providence Market Association', address: '1 Sims Ave', city: 'Providence', state: 'RI', zipcode: '', latitude: 41.824, longitude: -71.4128, parking_info: 'Lot parking available.', admission_info: 'Free admission.' },
  { name: 'Charleston Farmers Market', description: 'South Carolina growers and makers in Marion Square.', organizer_name: 'Charleston Market Association', address: '329 Meeting St', city: 'Charleston', state: 'SC', zipcode: '', latitude: 32.7765, longitude: -79.9311, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Sioux Falls Farmers Market', description: 'South Dakota farmers and artisans in downtown Sioux Falls.', organizer_name: 'Sioux Falls Market Association', address: '200 N Phillips Ave', city: 'Sioux Falls', state: 'SD', zipcode: '', latitude: 43.5446, longitude: -96.7311, parking_info: 'Free street parking.', admission_info: 'Free admission.' },
  { name: 'Nashville Farmers Market', description: 'Tennessee growers and food makers near Germantown.', organizer_name: 'Nashville Market Association', address: '900 Rosa L Parks Blvd', city: 'Nashville', state: 'TN', zipcode: '', latitude: 36.1627, longitude: -86.7816, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Austin Farmers Market', description: 'Texas farmers and makers in downtown Austin.', organizer_name: 'Austin Market Association', address: '422 Guadalupe St', city: 'Austin', state: 'TX', zipcode: '', latitude: 30.2672, longitude: -97.7431, parking_info: 'Paid garage parking.', admission_info: 'Free admission.' },
  { name: 'Salt Lake City Farmers Market', description: 'Utah growers and crafters in Pioneer Park.', organizer_name: 'Salt Lake City Market Association', address: '350 S 300 W', city: 'Salt Lake City', state: 'UT', zipcode: '', latitude: 40.7608, longitude: -111.891, parking_info: 'Street parking available.', admission_info: 'Free admission.' },
  { name: 'Burlington Farmers Market', description: 'Vermont farmers and artisans in City Hall Park.', organizer_name: 'Burlington Market Association', address: '149 Church St', city: 'Burlington', state: 'VT', zipcode: '', latitude: 44.4759, longitude: -73.2121, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Richmond Farmers Market', description: 'Virginia growers and makers in Shockoe Bottom.', organizer_name: 'Richmond Market Association', address: '100 N 17th St', city: 'Richmond', state: 'VA', zipcode: '', latitude: 37.5407, longitude: -77.436, parking_info: 'Lot parking available.', admission_info: 'Free admission.' },
  { name: 'Pike Place Farmers Market', description: 'Washington farmers and food makers at Pike Place.', organizer_name: 'Seattle Market Association', address: '85 Pike St', city: 'Seattle', state: 'WA', zipcode: '', latitude: 47.6062, longitude: -122.3321, parking_info: 'Paid garage parking.', admission_info: 'Free admission.' },
  { name: 'Charleston WV Farmers Market', description: 'West Virginia growers and crafters in Capitol Market.', organizer_name: 'Charleston WV Market Association', address: '800 Smith St', city: 'Charleston', state: 'WV', zipcode: '', latitude: 38.3498, longitude: -81.6326, parking_info: 'Free lot parking.', admission_info: 'Free admission.' },
  { name: 'Milwaukee Public Market', description: 'Wisconsin farmers and makers in the Historic Third Ward.', organizer_name: 'Milwaukee Market Association', address: '400 N Water St', city: 'Milwaukee', state: 'WI', zipcode: '', latitude: 43.0389, longitude: -87.9065, parking_info: 'Garage parking nearby.', admission_info: 'Free admission.' },
  { name: 'Cheyenne Farmers Market', description: 'Wyoming growers and artisans in downtown Cheyenne.', organizer_name: 'Cheyenne Market Association', address: '121 W 15th St', city: 'Cheyenne', state: 'WY', zipcode: '', latitude: 41.14, longitude: -104.8202, parking_info: 'Free street parking.', admission_info: 'Free admission.' },
  { name: 'DC Farmers Market at Dupont Circle', description: 'Growers and makers in the Dupont Circle neighborhood.', organizer_name: 'DC Market Association', address: '1500 20th St NW', city: 'Washington', state: 'DC', zipcode: '', latitude: 38.9097, longitude: -77.0434, parking_info: 'Street and garage parking.', admission_info: 'Free admission.' },
];

function main(): void {
  const rows: MarketCsvRow[] = BASELINE.map((row, index) => ({
    ...row,
    external_id: `baseline:${row.state}:${index}`,
    day_of_week: 'saturday',
    start_hour: 8,
    end_hour: 13,
    source: 'phase5_baseline',
  }));

  writeFileSync(OUTPUT, marketsToCsv(rows), 'utf8');
  console.log(`✔ Wrote ${rows.length} baseline markets to ${OUTPUT}`);
}

main();
